CREATE SCHEMA IF NOT EXISTS auth_schema AUTHORIZATION visitor;
CREATE SCHEMA IF NOT EXISTS registration_schema AUTHORIZATION visitor;
CREATE SCHEMA IF NOT EXISTS guard_schema AUTHORIZATION visitor;
CREATE SCHEMA IF NOT EXISTS dormitory_schema AUTHORIZATION visitor;
CREATE SCHEMA IF NOT EXISTS oa_integration_schema AUTHORIZATION visitor;
CREATE SCHEMA IF NOT EXISTS admin_query_schema AUTHORIZATION visitor;

