package com.wansheng.visitor.guard;
import static org.assertj.core.api.Assertions.assertThat;
import java.time.Instant; import org.flywaydb.core.Flyway; import org.h2.jdbcx.JdbcDataSource; import org.junit.jupiter.api.*; import org.springframework.jdbc.core.JdbcTemplate;
class GuardRepositoryTest{
 private JdbcTemplate jdbc;private GuardRepository repo;
 @BeforeEach void setup(){JdbcDataSource ds=new JdbcDataSource();ds.setURL("jdbc:h2:mem:guard;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");Flyway.configure().dataSource(ds).cleanDisabled(false).load().clean();Flyway.configure().dataSource(ds).load().migrate();jdbc=new JdbcTemplate(ds);repo=new GuardRepository(jdbc);jdbc.update("INSERT INTO guard_record(visit_id,visitor_name,mobile,host_name,vehicle_entering_factory,oa_status,guard_status,created_at) VALUES('V1','张三','13800138000','李经理',FALSE,'REJECTED','WAITING_ENTRY',CURRENT_TIMESTAMP)");}
 @Test void followsStateMachineAndAuditsOperator(){Instant t=Instant.parse("2026-08-24T01:00:00Z");assertThat(repo.transition("V1",GuardStatus.WAITING_ENTRY,GuardStatus.IN_FACTORY,"guard-a",t)).isOne();repo.updateOaStatus("V1","APPROVED");assertThat(repo.transition("V1",GuardStatus.WAITING_ENTRY,GuardStatus.IN_FACTORY,"guard-a",t)).isZero();assertThat(repo.transition("V1",GuardStatus.IN_FACTORY,GuardStatus.EXITED,"guard-b",t.plusSeconds(60))).isOne();GuardRecord r=repo.find("V1").orElseThrow();assertThat(r.guardStatus()).isEqualTo(GuardStatus.EXITED);assertThat(r.oaStatus()).isEqualTo("APPROVED");assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM guard_audit_log",Integer.class)).isEqualTo(2);assertThat(repo.unpublished()).extracting(GuardRepository.GuardOutboxEvent::eventType).containsExactly("VISITOR_ENTERED","VISITOR_EXITED");}
 @Test void createsAndUpdatesManualRecordWithAudit(){Instant t=Instant.parse("2026-08-24T01:00:00Z");GuardRecord r=new GuardRecord("GUARD-1","张三","13800138000","李经理",null,false,"NOT_STARTED",GuardStatus.WAITING_ENTRY,null,null,null,null);repo.createManual(r,"guard-a",t);assertThat(repo.updateDetails("GUARD-1",new GuardRecordRequest("张三丰","13900139000","王经理","浙A12345",true),"guard-b",t.plusSeconds(1))).isOne();GuardRecord updated=repo.find("GUARD-1").orElseThrow();assertThat(updated.visitorName()).isEqualTo("张三丰");assertThat(updated.vehicleEnteringFactory()).isTrue();assertThat(jdbc.queryForObject("SELECT COUNT(*) FROM guard_audit_log WHERE visit_id='GUARD-1'",Integer.class)).isEqualTo(2);}
}
