package com.wansheng.visitor.dormitory;

import static com.wansheng.visitor.dormitory.EmployeeDormitoryModels.*;
import static org.assertj.core.api.Assertions.*;
import java.time.LocalDate;
import java.time.ZoneId;
import org.flywaydb.core.Flyway;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.server.ResponseStatusException;

class EmployeeDormitoryServiceTest {
 private EmployeeDormitoryService service;
 private DormitoryExtensionService extension;
 private long buildingId,roomId,bedA,bedB,man,woman;
 @BeforeEach void setup(){JdbcDataSource ds=new JdbcDataSource();ds.setURL("jdbc:h2:mem:employeeDorm;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");Flyway.configure().dataSource(ds).cleanDisabled(false).load().clean();Flyway.configure().dataSource(ds).load().migrate();JdbcTemplate jdbc=new JdbcTemplate(ds);service=new EmployeeDormitoryService(new EmployeeDormitoryRepository(jdbc));extension=new DormitoryExtensionService(new DormitoryExtensionRepository(jdbc),service,System.getProperty("java.io.tmpdir")+"/dormitory-test-attachments");buildingId=service.addBuilding(new BuildingCommand("测试楼","测试区",true,99),"admin").id();roomId=service.addRoom(new RoomCommand(buildingId,"T01",2,"南","标间",true,false,null,null,null,null,1,null,true),"admin").id();bedA=service.addBed(new BedCommand(roomId,"靠窗","TEST-T01-A","公司提供",true),"admin").id();bedB=service.addBed(new BedCommand(roomId,"靠门","TEST-T01-B","公司提供",true),"admin").id();man=service.addPerson(new PersonCommand("张三","制造中心","生产部","男","新员工(普通)",null,null)).id();woman=service.addPerson(new PersonCommand("李四","制造中心","生产部","女","新员工(普通)",null,null)).id();}
 @Test void completesBookingCheckinTransferExtendAndCheckout(){Stay booked=service.book(book(man,bedA),"admin");assertThat(booked.status()).isEqualTo(StayStatus.BOOKED);assertThat(booked.threePiece()).isEqualTo("公司提供");assertThat(booked.threePieceNote()).isEqualTo("枕套待补");assertThat(booked.cleaningRequired()).isTrue();Stay in=service.checkIn(booked.id(),"admin");assertThat(in.checkedInAt()).isNotNull();Stay moved=service.transfer(in.id(),new TransferCommand(bedB,"换靠门床"),"admin");assertThat(moved.bed().id()).isEqualTo(bedB);Stay extended=service.extend(in.id(),new ExtendCommand(LocalDate.of(2026,10,1),"项目延期"),"admin");assertThat(extended.plannedMoveOut()).isEqualTo(LocalDate.of(2026,10,1));assertThat(service.checkout(in.id(),new CheckoutCommand(null,null,"正常退宿"),"admin").status()).isEqualTo(StayStatus.CHECKED_OUT);}
 @Test void updatesASelectedContinuousReservation(){Stay booked=service.book(book(man,bedA),"admin");UpdateStayCommand change=new UpdateStayCommand("张三改","制造中心","应用开发部","男","基地学习人员","工程师","P2","AP-2","李主管","长住房","自带","已登记",false,true,false,new java.math.BigDecimal("10"),new java.math.BigDecimal("20"),new java.math.BigDecimal("11"),new java.math.BigDecimal("22"),LocalDate.of(2026,9,2),LocalDate.of(2026,9,29),"说明","备注");Stay updated=service.updateStay(booked.id(),change,"admin");assertThat(updated.person().name()).isEqualTo("张三改");assertThat(updated.applicationCode()).isEqualTo("AP-2");assertThat(updated.cleaningRequired()).isFalse();assertThat(updated.moveOutElectric()).isEqualByComparingTo("22");}
 @Test void keepsBedCleaningStateUntilExplicitlyFinished(){Stay booked=service.book(book(man,bedA),"admin");assertThat(booked.bed().cleaningRequired()).isTrue();service.checkout(service.checkIn(booked.id(),"admin").id(),new CheckoutCommand(null,null,"退宿"),"admin");assertThat(service.tree().buildings().stream().flatMap(n->n.rooms().stream()).flatMap(r->r.beds().stream()).filter(b->b.id().equals(bedA)).findFirst().orElseThrow().cleaningRequired()).isTrue();assertThat(service.setBedCleaning(bedA,new CleaningCommand(false),"admin").cleaningRequired()).isFalse();}
 @Test void exposesReadableStayAuditTrail(){Stay booked=service.book(book(man,bedA),"admin");service.checkIn(booked.id(),"admin");service.transfer(booked.id(),new TransferCommand(bedB,"调宿测试"),"admin");assertThat(service.stayAudits()).extracting(StayAudit::action).contains("BOOK","CHECK_IN","TRANSFER");StayAudit transfer=service.stayAudits().stream().filter(a->a.action().equals("TRANSFER")).findFirst().orElseThrow();assertThat(transfer.personName()).isEqualTo("张三");assertThat(transfer.oldBedCode()).isEqualTo("TEST-T01-A");assertThat(transfer.newBedCode()).isEqualTo("TEST-T01-B");}
 @Test void savesAndUpdatesMonthlyRoomMeters(){service.saveMeterReadings(java.util.List.of(new MeterReadingCommand(roomId,"2026-08",new java.math.BigDecimal("12.50"),new java.math.BigDecimal("88.20"))),"admin");service.saveMeterReadings(java.util.List.of(new MeterReadingCommand(roomId,"2026-08",new java.math.BigDecimal("13.00"),new java.math.BigDecimal("90.00"))),"admin");assertThat(service.meterReadings("2026-08")).singleElement().satisfies(r->{assertThat(r.waterEnd()).isEqualByComparingTo("13.00");assertThat(r.operatorName()).isEqualTo("admin");});}
 @Test void returnsOnePersonsCompleteStayHistory(){service.book(book(man,bedA),"admin");assertThat(service.personStays(man)).singleElement().extracting(s->s.person().id()).isEqualTo(man);assertThat(service.personStays(woman)).isEmpty();}
 @Test void deletesOnlyTerminalStaysAndThenAllowsDeletingUnusedPerson(){Stay stay=service.book(book(man,bedA),"admin");assertThatThrownBy(()->service.deleteTerminalStay(stay.id(),"admin")).isInstanceOf(ResponseStatusException.class).hasMessageContaining("已取消或已退宿");assertThatThrownBy(()->service.deletePerson(man,"admin")).isInstanceOf(ResponseStatusException.class).hasMessageContaining("存在住宿记录");service.cancel(stay.id(),"admin");service.deleteTerminalStay(stay.id(),"admin");assertThatThrownBy(()->service.stay(stay.id())).isInstanceOf(ResponseStatusException.class);service.deletePerson(man,"admin");assertThat(service.people("张三")).isEmpty();assertThat(service.resourceAudits()).anySatisfy(a->{assertThat(a.resourceType()).isEqualTo("STAY");assertThat(a.action()).isEqualTo("DELETE");});}
 @Test void rejectsOccupiedBedAndMixedGenderRoom(){service.book(book(man,bedA),"admin");assertThatThrownBy(()->service.book(book(woman,bedA),"admin")).isInstanceOf(ResponseStatusException.class).hasMessageContaining("日期内存在冲突");assertThatThrownBy(()->service.book(book(woman,bedB),"admin")).isInstanceOf(ResponseStatusException.class).hasMessageContaining("男女混住");}
 @Test void allowsConsecutiveReservationsOnTheSameBed(){service.book(book(man,bedA,LocalDate.of(2026,9,1),LocalDate.of(2026,9,7)),"admin");Stay next=service.book(book(woman,bedA,LocalDate.of(2026,9,8),LocalDate.of(2026,9,11)),"admin");assertThat(next.plannedMoveIn()).isEqualTo(LocalDate.of(2026,9,8));}
 @Test void allowsOppositeGendersInAStandardRoomWhenTheirDatesDoNotOverlap(){service.book(book(man,bedA,LocalDate.of(2026,9,1),LocalDate.of(2026,9,7)),"admin");Stay next=service.book(book(woman,bedB,LocalDate.of(2026,9,8),LocalDate.of(2026,9,11)),"admin");assertThat(next.bed().id()).isEqualTo(bedB);}
 @Test void rejectsOverlappingReservationsOnTheSameBed(){service.book(book(man,bedA,LocalDate.of(2026,9,1),LocalDate.of(2026,9,7)),"admin");assertThatThrownBy(()->service.book(book(woman,bedA,LocalDate.of(2026,9,7),LocalDate.of(2026,9,11)),"admin")).isInstanceOf(ResponseStatusException.class).hasMessageContaining("存在冲突");}
 @Test void resourceTreePreservesBuildingRoomBedShape(){ResourceTree tree=service.tree();BuildingNode test=tree.buildings().stream().filter(n->n.building().name().equals("测试楼")).findFirst().orElseThrow();assertThat(test.rooms().get(0).beds()).extracting(Bed::label).containsExactly("靠窗","靠门");}
 @Test void occupiedResourcesCannotBeDisabledAndChangesAreAudited(){service.book(book(man,bedA),"admin");assertThatThrownBy(()->service.updateBed(bedA,new BedCommand(roomId,"靠窗","TEST-T01-A","公司提供",false),"admin")).isInstanceOf(ResponseStatusException.class).hasMessageContaining("不能移动或停用");assertThatThrownBy(()->service.updateRoom(roomId,new RoomCommand(buildingId,"T01",2,"南","标间",true,false,null,null,null,null,1,null,false),"admin")).isInstanceOf(ResponseStatusException.class).hasMessageContaining("不能移动或停用");assertThatThrownBy(()->service.updateBuilding(buildingId,new BuildingCommand("测试楼","测试区",false,99),"admin")).isInstanceOf(ResponseStatusException.class).hasMessageContaining("不能停用");assertThat(service.resourceAudits()).extracting(ResourceAudit::resourceType).contains("BUILDING","ROOM","BED");}
 @Test void importsPeopleAndResourcesWithDuplicateSummary(){ImportSummary people=service.importPeople(java.util.List.of(new PersonCommand("王五","技术中心","信息部","男","员工","开发","P3"),new PersonCommand("张三","制造中心","生产部","男","员工",null,null)),"admin");assertThat(people.peopleCreated()).isEqualTo(1);assertThat(people.skipped()).hasSize(1);ImportSummary resources=service.importResources(java.util.List.of(new ResourceImportCommand("导入楼","北区","101",1,"南","标间","A床","IMP-101-A","公司提供"),new ResourceImportCommand("导入楼","北区","101",1,"南","标间","B床","IMP-101-B","公司提供")),"admin");assertThat(resources.buildingsCreated()).isEqualTo(1);assertThat(resources.roomsCreated()).isEqualTo(1);assertThat(resources.bedsCreated()).isEqualTo(2);}
 @Test void importsCompleteStayRows(){StayImportCommand row=new StayImportCommand("导入住人员","总部","财务部","男","总部临时入住人员","会计","P2","测试楼","T01","TEST-T01-A","AP-X","赵主管","过渡房","自带","被套待补",false,true,true,new java.math.BigDecimal("1"),new java.math.BigDecimal("2"),null,null,LocalDate.of(2026,10,1),LocalDate.of(2026,10,3),"说明","备注",null);StayImportSummary summary=service.importStays(java.util.List.of(row),"admin");assertThat(summary.staysCreated()).isEqualTo(1);assertThat(summary.staysUpdated()).isZero();assertThat(summary.peopleCreated()).isEqualTo(1);assertThat(service.stays("BOOKED",buildingId,"导入住人员")).singleElement().satisfies(s->{assertThat(s.threePieceNote()).isEqualTo("被套待补");assertThat(s.cleaningRequired()).isTrue();});}
 @Test void reimportUpdatesMatchingActiveStayAndNormalizesCategory(){StayImportCommand first=new StayImportCommand("重复导入人员","研究院","应用开发与测试部","男","已审批长住人","应用主管","M2","测试楼","T01","TEST-T01-A",null,null,"长住房","自带",null,false,null,false,null,null,null,null,LocalDate.of(2026,3,16),null,null,null,null);service.importStays(java.util.List.of(first),"admin");StayImportCommand latest=new StayImportCommand("重复导入人员","研究院","应用开发与测试部","男","已审批长住人","高级应用主管","M3","测试楼","T01","TEST-T01-A","20260001","陈主管","长住房","自带","已补齐",true,true,false,null,null,null,null,LocalDate.of(2026,3,16),null,"最新说明","最新备注","已入住");StayImportSummary summary=service.importStays(java.util.List.of(latest),"admin");assertThat(summary.staysCreated()).isZero();assertThat(summary.staysUpdated()).isEqualTo(1);assertThat(service.stays("CHECKED_IN",buildingId,"重复导入人员")).singleElement().satisfies(s->{assertThat(s.person().category()).isEqualTo("己审批长住员工");assertThat(s.person().positionName()).isEqualTo("高级应用主管");assertThat(s.applicationCode()).isEqualTo("20260001");assertThat(s.threePieceNote()).isEqualTo("已补齐");});}
 @Test void importsBlankNameAndMoveInUsingSafeDefaults(){StayImportCommand row=new StayImportCommand("","总部","财务部",null,"总部临时入住人员",null,null,"测试楼","T01","TEST-T01-A",null,null,"过渡房",null,null,false,null,false,null,null,null,null,null,null,null,null,null);StayImportSummary summary=service.importStays(java.util.List.of(row),"admin");assertThat(summary.staysCreated()).isEqualTo(1);assertThat(service.stays("CHECKED_IN",buildingId,"未填写")).singleElement().satisfies(s->{assertThat(s.person().name()).isEqualTo("未填写");assertThat(s.plannedMoveIn()).isEqualTo(LocalDate.now(ZoneId.of("Asia/Shanghai")));});}
 @Test void savesBookingWhenEveryEditableFieldIsBlank(){Person person=service.addPerson(new PersonCommand("","","",null,"","",""));Stay stay=service.book(new BookCommand(person.id(),bedA,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null),"admin");assertThat(stay.person().name()).isEqualTo("未填写");assertThat(stay.person().department()).isEqualTo("未填写");assertThat(stay.person().gender()).isEqualTo("未填写");assertThat(stay.person().category()).isEqualTo("未分类");assertThat(stay.bedType()).isEqualTo("未填写");assertThat(stay.costCut()).isFalse();assertThat(stay.cleaningRequired()).isFalse();assertThat(stay.plannedMoveIn()).isEqualTo(LocalDate.now(ZoneId.of("Asia/Shanghai")));}
 @Test void importsStayWhenOnlyBedCodeIsFilled(){StayImportCommand row=new StayImportCommand(null,null,null,null,null,null,null,null,null,"TEST-T01-A",null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);StayImportSummary summary=service.importStays(java.util.List.of(row),"admin");assertThat(summary.staysCreated()).isEqualTo(1);assertThat(summary.skipped()).isEmpty();assertThat(service.stays("CHECKED_IN",buildingId,"未填写")).singleElement().satisfies(s->{assertThat(s.person().department()).isEqualTo("未填写");assertThat(s.bedType()).isEqualTo("标间");});}
 @Test void skipsOptionalRowWithoutBedCode(){StayImportCommand row=new StayImportCommand(null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null,null);StayImportSummary summary=service.importStays(java.util.List.of(row),"admin");assertThat(summary.staysCreated()).isZero();assertThat(summary.peopleCreated()).isZero();assertThat(summary.skipped()).containsExactly("第2行：床位编码为空，未创建住宿记录");}
 @Test void calculatesDormitoryStatistics(){service.book(book(man,bedA),"admin");DormitoryStatistics stats=service.statistics();assertThat(stats.summary().booked()).isEqualTo(1);assertThat(stats.summary().freeBeds()).isGreaterThanOrEqualTo(1);assertThat(stats.buildings()).anySatisfy(x->{assertThat(x.name()).isEqualTo("测试楼");assertThat(x.active()).isEqualTo(1);});}
 @Test void excludesDisabledBuildingsRoomsAndBedsFromEffectiveStatistics(){service.book(book(man,bedA),"admin");DormitoryStatistics baseline=service.statistics();long disabledBed=service.addBed(new BedCommand(roomId,"备用床","TEST-T01-C",null,true),"admin").id();service.updateBed(disabledBed,new BedCommand(roomId,"备用床","TEST-T01-C",null,false),"admin");long disabledRoom=service.addRoom(new RoomCommand(buildingId,"T02",2,"南","单间",true,false,null,null,null,null,2,null,true),"admin").id();service.addBed(new BedCommand(disabledRoom,"单床","TEST-T02-A",null,true),"admin");service.updateRoom(disabledRoom,new RoomCommand(buildingId,"T02",2,"南","单间",true,false,null,null,null,null,2,null,false),"admin");long disabledBuilding=service.addBuilding(new BuildingCommand("停用楼","测试区",true,100),"admin").id();long disabledBuildingRoom=service.addRoom(new RoomCommand(disabledBuilding,"101",1,"南","单间",true,false,null,null,null,null,1,null,true),"admin").id();service.addBed(new BedCommand(disabledBuildingRoom,"单床","OFF-101-A",null,true),"admin");service.updateBuilding(disabledBuilding,new BuildingCommand("停用楼","测试区",false,100),"admin");DormitoryStatistics stats=service.statistics();assertThat(stats.summary().buildings()).isEqualTo(baseline.summary().buildings());assertThat(stats.summary().rooms()).isEqualTo(baseline.summary().rooms());assertThat(stats.summary().beds()).isEqualTo(baseline.summary().beds());assertThat(stats.summary().freeBeds()).isEqualTo(baseline.summary().freeBeds());assertThat(stats.buildings()).extracting(StatisticsItem::name).doesNotContain("停用楼");assertThat(stats.buildings().stream().filter(x->x.name().equals("测试楼")).findFirst().orElseThrow().total()).isEqualTo(2);}
 @Test void storesAttachmentsAndGeneratesFeeBills(){Stay stay=service.book(book(man,bedA),"admin");var file=new org.springframework.mock.web.MockMultipartFile("file","申请单.pdf","application/pdf","pdf".getBytes());StayAttachment attachment=extension.upload(stay.id(),"APPLICATION",file,"admin");assertThat(extension.attachments(stay.id())).extracting(StayAttachment::id).contains(attachment.id());service.saveMeterReadings(java.util.List.of(new MeterReadingCommand(roomId,"2026-08",new java.math.BigDecimal("10"),new java.math.BigDecimal("100"))),"admin");service.saveMeterReadings(java.util.List.of(new MeterReadingCommand(roomId,"2026-09",new java.math.BigDecimal("15"),new java.math.BigDecimal("120"))),"admin");extension.saveFeeRule(new FeeRuleCommand(new java.math.BigDecimal("3"),new java.math.BigDecimal("0.5"),new java.math.BigDecimal("1"),new java.math.BigDecimal("5"),true),"admin");FeeBill bill=extension.generate("2026-09","admin").stream().filter(x->x.roomId().equals(roomId)).findFirst().orElseThrow();assertThat(bill.occupantNames()).contains("张三");assertThat(bill.waterAmount()).isEqualByComparingTo("12.00");assertThat(bill.electricAmount()).isEqualByComparingTo("7.50");extension.updateBill(bill.id(),new FeeBillCommand(new java.math.BigDecimal("-2"),"减免","CONFIRMED"),"admin");assertThat(extension.bills("2026-09").stream().filter(x->x.id().equals(bill.id())).findFirst().orElseThrow().totalAmount()).isEqualByComparingTo("17.50");extension.delete(attachment.id());}
 @Test void generatesLockedPersonLevelMonthlySettlementAndReversal(){long second=service.addPerson(new PersonCommand("王五","制造中心","生产部","男","新员工(普通)",null,null)).id();service.book(book(man,bedA,LocalDate.of(2026,9,1),LocalDate.of(2026,10,1)),"admin");service.book(book(second,bedB,LocalDate.of(2026,9,1),LocalDate.of(2026,10,1)),"admin");service.saveMeterReadings(java.util.List.of(new MeterReadingCommand(roomId,"2026-08",new java.math.BigDecimal("100"),new java.math.BigDecimal("200"))),"admin");service.saveMeterReadings(java.util.List.of(new MeterReadingCommand(roomId,"2026-09",new java.math.BigDecimal("110"),new java.math.BigDecimal("220"))),"admin");FeeSettlementResult generated=extension.generateSettlements("2026-09","admin");assertThat(generated.entries()).hasSize(2).allSatisfy(e->{assertThat(e.occupiedDays()).isEqualTo(30);assertThat(e.chargeableDays()).isEqualTo(30);assertThat(e.waterUsage()).isEqualByComparingTo("5.0000");assertThat(e.electricUsage()).isEqualByComparingTo("10.0000");assertThat(e.freeElectricUsage()).isEqualByComparingTo("2.5000");assertThat(e.waterAmount()).isEqualByComparingTo("75.00");assertThat(e.electricAmount()).isEqualByComparingTo("5.25");assertThat(e.totalAmount()).isEqualByComparingTo("80.25");});FeeSettlementResult reversal=extension.reverseSettlement(generated.batch().id(),new FeeReversalCommand("抄表录入错误"),"admin");assertThat(reversal.batch().status()).isEqualTo("REVERSAL");assertThat(reversal.entries()).allSatisfy(e->assertThat(e.totalAmount()).isEqualByComparingTo("-80.25"));assertThatThrownBy(()->extension.reverseSettlement(generated.batch().id(),new FeeReversalCommand("重复"),"admin")).isInstanceOf(ResponseStatusException.class).hasMessageContaining("已经冲正");}
 @Test void keepsNewResidentFreeUntilContinuousStayReachesFifteenDays(){service.book(book(man,bedA,LocalDate.of(2026,9,20),LocalDate.of(2026,10,1)),"admin");service.saveMeterReadings(java.util.List.of(new MeterReadingCommand(roomId,"2026-08",java.math.BigDecimal.ZERO,java.math.BigDecimal.ZERO)),"admin");service.saveMeterReadings(java.util.List.of(new MeterReadingCommand(roomId,"2026-09",java.math.BigDecimal.ONE,new java.math.BigDecimal("10"))),"admin");FeeSettlementEntry entry=extension.generateSettlements("2026-09","admin").entries().get(0);assertThat(entry.occupiedDays()).isEqualTo(11);assertThat(entry.chargeableDays()).isZero();assertThat(entry.totalAmount()).isEqualByComparingTo("0.00");}
 private BookCommand book(long person,long bed){return new BookCommand(person,bed,"AP-1","王主管","过渡房","公司提供","枕套待补",true,false,true,null,null,null,null,LocalDate.of(2026,9,1),LocalDate.of(2026,9,30),null,null);}
 private BookCommand book(long person,long bed,LocalDate in,LocalDate out){return new BookCommand(person,bed,"AP-1","王主管","过渡房","公司提供",null,true,false,false,null,null,null,null,in,out,null,null);}
}
