package com.wansheng.visitor.dormitory;

import static com.wansheng.visitor.dormitory.EmployeeDormitoryModels.*;
import static org.assertj.core.api.Assertions.*;
import java.time.LocalDate;
import org.flywaydb.core.Flyway;
import org.h2.jdbcx.JdbcDataSource;
import org.junit.jupiter.api.*;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.web.server.ResponseStatusException;

class EmployeeDormitoryServiceTest {
 private EmployeeDormitoryService service;
 private DormitoryExtensionService extension;
 private long buildingId,roomId,bedA,bedB,man,woman;
 @BeforeEach void setup(){JdbcDataSource ds=new JdbcDataSource();ds.setURL("jdbc:h2:mem:employeeDorm;MODE=PostgreSQL;DB_CLOSE_DELAY=-1");Flyway.configure().dataSource(ds).cleanDisabled(false).load().clean();Flyway.configure().dataSource(ds).load().migrate();JdbcTemplate jdbc=new JdbcTemplate(ds);service=new EmployeeDormitoryService(new EmployeeDormitoryRepository(jdbc));extension=new DormitoryExtensionService(new DormitoryExtensionRepository(jdbc),service,System.getProperty("java.io.tmpdir")+"/dormitory-test-attachments");buildingId=service.addBuilding(new BuildingCommand("测试楼","测试区",true,99),"admin").id();roomId=service.addRoom(new RoomCommand(buildingId,"T01",2,"南","标间",true,false,null,null,null,null,1,null,true),"admin").id();bedA=service.addBed(new BedCommand(roomId,"靠窗","TEST-T01-A","公司提供",true),"admin").id();bedB=service.addBed(new BedCommand(roomId,"靠门","TEST-T01-B","公司提供",true),"admin").id();man=service.addPerson(new PersonCommand("张三","制造中心","生产部","男","新员工(普通)",null,null)).id();woman=service.addPerson(new PersonCommand("李四","制造中心","生产部","女","新员工(普通)",null,null)).id();}
 @Test void completesBookingCheckinTransferExtendAndCheckout(){Stay booked=service.book(book(man,bedA),"admin");assertThat(booked.status()).isEqualTo(StayStatus.BOOKED);Stay in=service.checkIn(booked.id(),"admin");assertThat(in.checkedInAt()).isNotNull();Stay moved=service.transfer(in.id(),new TransferCommand(bedB,"换靠门床"),"admin");assertThat(moved.bed().id()).isEqualTo(bedB);Stay extended=service.extend(in.id(),new ExtendCommand(LocalDate.of(2026,10,1),"项目延期"),"admin");assertThat(extended.plannedMoveOut()).isEqualTo(LocalDate.of(2026,10,1));assertThat(service.checkout(in.id(),new CheckoutCommand(null,null,"正常退宿"),"admin").status()).isEqualTo(StayStatus.CHECKED_OUT);}
 @Test void exposesReadableStayAuditTrail(){Stay booked=service.book(book(man,bedA),"admin");service.checkIn(booked.id(),"admin");service.transfer(booked.id(),new TransferCommand(bedB,"调宿测试"),"admin");assertThat(service.stayAudits()).extracting(StayAudit::action).contains("BOOK","CHECK_IN","TRANSFER");StayAudit transfer=service.stayAudits().stream().filter(a->a.action().equals("TRANSFER")).findFirst().orElseThrow();assertThat(transfer.personName()).isEqualTo("张三");assertThat(transfer.oldBedCode()).isEqualTo("TEST-T01-A");assertThat(transfer.newBedCode()).isEqualTo("TEST-T01-B");}
 @Test void savesAndUpdatesMonthlyRoomMeters(){service.saveMeterReadings(java.util.List.of(new MeterReadingCommand(roomId,"2026-08",new java.math.BigDecimal("12.50"),new java.math.BigDecimal("88.20"))),"admin");service.saveMeterReadings(java.util.List.of(new MeterReadingCommand(roomId,"2026-08",new java.math.BigDecimal("13.00"),new java.math.BigDecimal("90.00"))),"admin");assertThat(service.meterReadings("2026-08")).singleElement().satisfies(r->{assertThat(r.waterEnd()).isEqualByComparingTo("13.00");assertThat(r.operatorName()).isEqualTo("admin");});}
 @Test void returnsOnePersonsCompleteStayHistory(){service.book(book(man,bedA),"admin");assertThat(service.personStays(man)).singleElement().extracting(s->s.person().id()).isEqualTo(man);assertThat(service.personStays(woman)).isEmpty();}
 @Test void rejectsOccupiedBedAndMixedGenderRoom(){service.book(book(man,bedA),"admin");assertThatThrownBy(()->service.book(book(woman,bedA),"admin")).isInstanceOf(ResponseStatusException.class).hasMessageContaining("床位已被");assertThatThrownBy(()->service.book(book(woman,bedB),"admin")).isInstanceOf(ResponseStatusException.class).hasMessageContaining("男女混住");}
 @Test void resourceTreePreservesBuildingRoomBedShape(){ResourceTree tree=service.tree();BuildingNode test=tree.buildings().stream().filter(n->n.building().name().equals("测试楼")).findFirst().orElseThrow();assertThat(test.rooms().get(0).beds()).extracting(Bed::label).containsExactly("靠窗","靠门");}
 @Test void occupiedResourcesCannotBeDisabledAndChangesAreAudited(){service.book(book(man,bedA),"admin");assertThatThrownBy(()->service.updateBed(bedA,new BedCommand(roomId,"靠窗","TEST-T01-A","公司提供",false),"admin")).isInstanceOf(ResponseStatusException.class).hasMessageContaining("不能移动或停用");assertThatThrownBy(()->service.updateRoom(roomId,new RoomCommand(buildingId,"T01",2,"南","标间",true,false,null,null,null,null,1,null,false),"admin")).isInstanceOf(ResponseStatusException.class).hasMessageContaining("不能移动或停用");assertThatThrownBy(()->service.updateBuilding(buildingId,new BuildingCommand("测试楼","测试区",false,99),"admin")).isInstanceOf(ResponseStatusException.class).hasMessageContaining("不能停用");assertThat(service.resourceAudits()).extracting(ResourceAudit::resourceType).contains("BUILDING","ROOM","BED");}
 @Test void importsPeopleAndResourcesWithDuplicateSummary(){ImportSummary people=service.importPeople(java.util.List.of(new PersonCommand("王五","技术中心","信息部","男","员工","开发","P3"),new PersonCommand("张三","制造中心","生产部","男","员工",null,null)),"admin");assertThat(people.peopleCreated()).isEqualTo(1);assertThat(people.skipped()).hasSize(1);ImportSummary resources=service.importResources(java.util.List.of(new ResourceImportCommand("导入楼","北区","101",1,"南","标间","A床","IMP-101-A","公司提供"),new ResourceImportCommand("导入楼","北区","101",1,"南","标间","B床","IMP-101-B","公司提供")),"admin");assertThat(resources.buildingsCreated()).isEqualTo(1);assertThat(resources.roomsCreated()).isEqualTo(1);assertThat(resources.bedsCreated()).isEqualTo(2);}
 @Test void calculatesDormitoryStatistics(){service.book(book(man,bedA),"admin");DormitoryStatistics stats=service.statistics();assertThat(stats.summary().booked()).isEqualTo(1);assertThat(stats.summary().freeBeds()).isGreaterThanOrEqualTo(1);assertThat(stats.buildings()).anySatisfy(x->{assertThat(x.name()).isEqualTo("测试楼");assertThat(x.active()).isEqualTo(1);});}
 @Test void storesAttachmentsAndGeneratesFeeBills(){Stay stay=service.book(book(man,bedA),"admin");var file=new org.springframework.mock.web.MockMultipartFile("file","申请单.pdf","application/pdf","pdf".getBytes());StayAttachment attachment=extension.upload(stay.id(),"APPLICATION",file,"admin");assertThat(extension.attachments(stay.id())).extracting(StayAttachment::id).contains(attachment.id());service.saveMeterReadings(java.util.List.of(new MeterReadingCommand(roomId,"2026-08",new java.math.BigDecimal("10"),new java.math.BigDecimal("100"))),"admin");service.saveMeterReadings(java.util.List.of(new MeterReadingCommand(roomId,"2026-09",new java.math.BigDecimal("15"),new java.math.BigDecimal("120"))),"admin");extension.saveFeeRule(new FeeRuleCommand(new java.math.BigDecimal("3"),new java.math.BigDecimal("0.5"),new java.math.BigDecimal("1"),new java.math.BigDecimal("5"),true),"admin");FeeBill bill=extension.generate("2026-09","admin").stream().filter(x->x.roomId().equals(roomId)).findFirst().orElseThrow();assertThat(bill.occupantNames()).contains("张三");assertThat(bill.waterAmount()).isEqualByComparingTo("12.00");assertThat(bill.electricAmount()).isEqualByComparingTo("7.50");extension.updateBill(bill.id(),new FeeBillCommand(new java.math.BigDecimal("-2"),"减免","CONFIRMED"),"admin");assertThat(extension.bills("2026-09").stream().filter(x->x.id().equals(bill.id())).findFirst().orElseThrow().totalAmount()).isEqualByComparingTo("17.50");extension.delete(attachment.id());}
 private BookCommand book(long person,long bed){return new BookCommand(person,bed,"AP-1","王主管","过渡房",true,false,null,null,LocalDate.of(2026,9,1),LocalDate.of(2026,9,30),null,null);}
}
