CREATE TABLE dorm_fee_settlement_batch (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 billing_month VARCHAR(7) NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'GENERATED',
 source_batch_id BIGINT REFERENCES dorm_fee_settlement_batch(id),
 remark VARCHAR(500),
 operator_name VARCHAR(100) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_fee_settlement_batch_month ON dorm_fee_settlement_batch(billing_month, created_at);

CREATE TABLE dorm_fee_settlement_entry (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 batch_id BIGINT NOT NULL REFERENCES dorm_fee_settlement_batch(id),
 stay_id BIGINT NOT NULL REFERENCES dorm_stay(id),
 person_id BIGINT NOT NULL REFERENCES dorm_person(id),
 room_id BIGINT NOT NULL REFERENCES dorm_room(id),
 building_name VARCHAR(100) NOT NULL,
 room_no VARCHAR(50) NOT NULL,
 billing_month VARCHAR(7) NOT NULL,
 occupied_days INTEGER NOT NULL,
 chargeable_days INTEGER NOT NULL,
 occupant_count INTEGER NOT NULL,
 water_usage DECIMAL(14,4) NOT NULL DEFAULT 0,
 electric_usage DECIMAL(14,4) NOT NULL DEFAULT 0,
 free_electric_usage DECIMAL(14,4) NOT NULL DEFAULT 0,
 water_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
 electric_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
 total_amount DECIMAL(14,2) NOT NULL DEFAULT 0,
 correction_of BIGINT REFERENCES dorm_fee_settlement_entry(id),
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_fee_settlement_entry_month ON dorm_fee_settlement_entry(billing_month, person_id, room_id);
CREATE INDEX idx_fee_settlement_entry_stay ON dorm_fee_settlement_entry(stay_id);
