CREATE TABLE dorm_resource_audit (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 resource_type VARCHAR(30) NOT NULL,
 resource_id BIGINT NOT NULL,
 action VARCHAR(30) NOT NULL,
 before_value TEXT,
 after_value TEXT,
 operator_name VARCHAR(100) NOT NULL,
 operated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_dorm_resource_audit_resource ON dorm_resource_audit(resource_type,resource_id);
