CREATE TABLE dorm_meter_reading (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 room_id BIGINT NOT NULL REFERENCES dorm_room(id),
 reading_month VARCHAR(7) NOT NULL,
 water_end DECIMAL(14,2),
 electric_end DECIMAL(14,2),
 operator_name VARCHAR(100) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(room_id, reading_month)
);
CREATE INDEX idx_dorm_meter_month ON dorm_meter_reading(reading_month);
