CREATE TABLE dorm_stay_attachment (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 stay_id BIGINT NOT NULL REFERENCES dorm_stay(id),
 attachment_type VARCHAR(30) NOT NULL,
 original_name VARCHAR(255) NOT NULL,
 stored_name VARCHAR(100) NOT NULL UNIQUE,
 content_type VARCHAR(120) NOT NULL,
 file_size BIGINT NOT NULL,
 operator_name VARCHAR(100) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);
CREATE INDEX idx_dorm_attachment_stay ON dorm_stay_attachment(stay_id,created_at);

CREATE TABLE dorm_fee_rule (
 id BIGINT PRIMARY KEY,
 water_price DECIMAL(12,4) NOT NULL DEFAULT 0,
 electric_price DECIMAL(12,4) NOT NULL DEFAULT 0,
 free_water DECIMAL(12,2) NOT NULL DEFAULT 0,
 free_electric DECIMAL(12,2) NOT NULL DEFAULT 0,
 enabled BOOLEAN NOT NULL DEFAULT FALSE,
 operator_name VARCHAR(100) NOT NULL,
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 CONSTRAINT ck_fee_rule_nonnegative CHECK(water_price>=0 AND electric_price>=0 AND free_water>=0 AND free_electric>=0)
);
INSERT INTO dorm_fee_rule(id,operator_name) VALUES(1,'system');

CREATE TABLE dorm_fee_bill (
 id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
 room_id BIGINT NOT NULL REFERENCES dorm_room(id),
 billing_month VARCHAR(7) NOT NULL,
 water_usage DECIMAL(14,2) NOT NULL,
 electric_usage DECIMAL(14,2) NOT NULL,
 water_price DECIMAL(12,4) NOT NULL,
 electric_price DECIMAL(12,4) NOT NULL,
 free_water DECIMAL(12,2) NOT NULL,
 free_electric DECIMAL(12,2) NOT NULL,
 water_amount DECIMAL(14,2) NOT NULL,
 electric_amount DECIMAL(14,2) NOT NULL,
 adjustment DECIMAL(14,2) NOT NULL DEFAULT 0,
 total_amount DECIMAL(14,2) NOT NULL,
 status VARCHAR(20) NOT NULL DEFAULT 'DRAFT',
 remark VARCHAR(500),
 operator_name VARCHAR(100) NOT NULL,
 created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
 UNIQUE(room_id,billing_month)
);
CREATE INDEX idx_dorm_fee_bill_month ON dorm_fee_bill(billing_month,status);
