CREATE TABLE visitor_registration (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    visit_id VARCHAR(40) NOT NULL UNIQUE,
    visitor_name VARCHAR(100) NOT NULL,
    mobile VARCHAR(30) NOT NULL,
    identity_card_number VARCHAR(255),
    host_name VARCHAR(100) NOT NULL,
    host_department VARCHAR(150) NOT NULL,
    visit_reason VARCHAR(500) NOT NULL,
    accommodation_required BOOLEAN NOT NULL,
    has_vehicle BOOLEAN NOT NULL,
    plate_number VARCHAR(30),
    vehicle_entering_factory BOOLEAN NOT NULL,
    phone_notification_requested BOOLEAN NOT NULL,
    registration_status VARCHAR(30) NOT NULL,
    oa_status VARCHAR(30) NOT NULL,
    registered_at TIMESTAMP WITH TIME ZONE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_registration_registered_at ON visitor_registration (registered_at);
CREATE INDEX idx_registration_mobile ON visitor_registration (mobile);

CREATE TABLE registration_outbox (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id VARCHAR(50) NOT NULL UNIQUE,
    event_type VARCHAR(80) NOT NULL,
    visit_id VARCHAR(40) NOT NULL,
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    event_version INTEGER NOT NULL,
    published_at TIMESTAMP WITH TIME ZONE,
    retry_count INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(1000)
);

CREATE INDEX idx_outbox_unpublished ON registration_outbox (published_at, id);

