package com.wansheng.visitor.admin;
import tools.jackson.databind.*;import java.time.*;import java.util.*;import org.springframework.beans.factory.annotation.Value;import org.springframework.web.bind.annotation.*;import org.springframework.web.client.RestClient;
@RestController @RequestMapping("/api/visitor/admin")class AdminQueryController{
 private final RestClient client;private final String registration,guard,dorm,token;private final ZoneId businessZone;AdminQueryController(@Value("${visitor.admin.registration-url}")String r,@Value("${visitor.admin.guard-url}")String g,@Value("${visitor.admin.dormitory-url}")String d,@Value("${visitor.admin.internal-token}")String t,@Value("${visitor.admin.business-zone:Asia/Shanghai}")String zone){client=RestClient.builder().build();registration=r;guard=g;dorm=d;token=t;businessZone=ZoneId.of(zone);}
 private JsonNode get(String url){return client.get().uri(url).header("X-Internal-Token",token).retrieve().body(JsonNode.class);}
 @GetMapping("/registrations")JsonNode registrations(){return get(registration+"/internal/registrations/admin-view?limit=200");}
 @GetMapping("/guard-records")JsonNode guards(){return get(guard+"/internal/guard/records");}
 @GetMapping("/dormitory-records")JsonNode dormitory(){return get(dorm+"/internal/dormitory/records");}
 @GetMapping("/audit-logs")List<JsonNode> audits(){List<JsonNode>all=new ArrayList<>();get(guard+"/internal/guard/audits").forEach(all::add);get(dorm+"/internal/dormitory/audits").forEach(all::add);return all;}
 @GetMapping("/dashboard")Map<String,Integer> dashboard(){return calculateDashboard(registrations(),guards(),dormitory(),LocalDate.now(businessZone),businessZone);}
 static Map<String,Integer> calculateDashboard(JsonNode rs,JsonNode gs,JsonNode ds,LocalDate today,ZoneId zone){int registrationsToday=0,waiting=0,inFactory=0,exitedToday=0,needsDorm=0,pendingBed=0,currentDorm=0;for(JsonNode r:rs)if(onDate(r.path("registeredAt"),today,zone))registrationsToday++;for(JsonNode g:gs){switch(g.path("guardStatus").asText()){case"WAITING_ENTRY"->waiting++;case"IN_FACTORY"->inFactory++;case"EXITED"->{if(onDate(g.path("exitTime"),today,zone))exitedToday++;}}}for(JsonNode d:ds)if(d.path("accommodationRequired").asBoolean()){needsDorm++;if(d.path("bedCode").isMissingNode()||d.path("bedCode").isNull())pendingBed++;else currentDorm++;}return Map.of("todayRegistrations",registrationsToday,"waitingEntry",waiting,"inFactory",inFactory,"exited",exitedToday,"needsAccommodation",needsDorm,"pendingBed",pendingBed,"currentAccommodation",currentDorm);}
 private static boolean onDate(JsonNode value,LocalDate date,ZoneId zone){return value!=null&&!value.isMissingNode()&&!value.isNull()&&!value.asText().isBlank()&&Instant.parse(value.asText()).atZone(zone).toLocalDate().equals(date);}
}
