package com.wansheng.visitor.oa;
import com.fasterxml.jackson.databind.*;import java.time.*;import org.springframework.amqp.rabbit.annotation.RabbitListener;import org.springframework.beans.factory.annotation.Value;import org.springframework.dao.DuplicateKeyException;import org.springframework.jdbc.core.JdbcTemplate;import org.springframework.stereotype.Service;import org.springframework.transaction.annotation.Transactional;import org.springframework.web.client.RestClient;
@Service class OaProcessService{
 private final OaAdapter adapter;private final JdbcTemplate jdbc;private final RestClient client;private final ObjectMapper json;private final String registrationUrl,token;private final Clock clock=Clock.systemUTC();
 OaProcessService(OaAdapter a,JdbcTemplate j,RestClient.Builder b,ObjectMapper o,@Value("${visitor.oa.registration-service-url}")String u,@Value("${visitor.oa.internal-token}")String t){adapter=a;jdbc=j;client=b.build();json=o;registrationUrl=u;token=t;}
 @RabbitListener(queues="oa.visitor-registered") @Transactional void receive(String payload)throws Exception{JsonNode e=json.readTree(payload);String eid=e.path("eventId").asText(),vid=e.path("visitId").asText();if(eid.isBlank()||vid.isBlank())throw new IllegalArgumentException("invalid event");try{client.get().uri(registrationUrl+"/internal/registrations/{id}/oa-view",vid).header("X-Internal-Token",token).retrieve().toBodilessEntity();OaAdapter.Submission s=adapter.submit(new OaAdapter.OaApplication(vid));Instant now=clock.instant();jdbc.update("INSERT INTO oa_process(event_id,visit_id,external_process_id,oa_status,attempt_count,created_at,updated_at) VALUES(?,?,?,?,1,?,?)",eid,vid,s.externalProcessId(),s.status(),now,now);updateRegistration(vid,s.status());}catch(DuplicateKeyException ignored){}}
 @Transactional void updateStatus(String visitId,String status){if(!java.util.Set.of("APPROVED","REJECTED","FAILED").contains(status))throw new IllegalArgumentException("invalid OA status");int n=jdbc.update("UPDATE oa_process SET oa_status=?,updated_at=? WHERE visit_id=?",status,clock.instant(),visitId);if(n!=1)throw new IllegalArgumentException("OA process not found");updateRegistration(visitId,status);}
 private void updateRegistration(String vid,String status){client.put().uri(registrationUrl+"/internal/registrations/{id}/oa-status",vid).header("X-Internal-Token",token).body(java.util.Map.of("status",status)).retrieve().toBodilessEntity();}
}

