CREATE TABLE guard_record (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_id VARCHAR(40) NOT NULL UNIQUE,
  visitor_name VARCHAR(100) NOT NULL,
  mobile VARCHAR(30) NOT NULL,
  host_name VARCHAR(100) NOT NULL,
  plate_number VARCHAR(30),
  vehicle_entering_factory BOOLEAN NOT NULL,
  oa_status VARCHAR(30) NOT NULL,
  guard_status VARCHAR(30) NOT NULL,
  entry_time TIMESTAMP WITH TIME ZONE,
  exit_time TIMESTAMP WITH TIME ZONE,
  entry_operator VARCHAR(100),
  exit_operator VARCHAR(100),
  version INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE INDEX idx_guard_status ON guard_record (guard_status, created_at);

CREATE TABLE guard_processed_event (
  event_id VARCHAR(50) PRIMARY KEY,
  processed_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE guard_audit_log (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  visit_id VARCHAR(40) NOT NULL,
  action VARCHAR(40) NOT NULL,
  operator_name VARCHAR(100) NOT NULL,
  operated_at TIMESTAMP WITH TIME ZONE NOT NULL
);
CREATE TABLE guard_outbox(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,event_id VARCHAR(50) NOT NULL UNIQUE,event_type VARCHAR(80) NOT NULL,visit_id VARCHAR(40) NOT NULL,occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,published_at TIMESTAMP WITH TIME ZONE);
