export type Building={id:number;name:string;regionName:string;enabled:boolean;displayOrder:number}
export type Bed={id:number;roomId:number;label:string;bedCode:string;threePiece?:string;enabled:boolean}
export type Room={id:number;buildingId:number;roomNo:string;floorNo:number;facing?:string;roomType:string;livable:boolean;cleaningRequired:boolean;gridCol?:number;gridRow?:number;gridColSpan?:number;gridRowSpan?:number;displayOrder:number;specialNote?:string;enabled:boolean;beds:Bed[]}
export type BuildingNode={building:Building;rooms:Room[]}
export type Person={id:number;name:string;centerName?:string;department:string;gender:'男'|'女';category:string;positionName?:string;rankName?:string}
export type Stay={id:number;person:Person;bed:Bed;status:'BOOKED'|'CHECKED_IN'|'CHECKED_OUT'|'CANCELLED';applicationCode?:string;liaison?:string;bedType:string;costCut:boolean;promiseSigned?:boolean;moveInWater?:number;moveInElectric?:number;moveOutWater?:number;moveOutElectric?:number;plannedMoveIn:string;plannedMoveOut?:string;checkedInAt?:string;checkedOutAt?:string;specialNote?:string;remark?:string}
export type StayAudit={id:number;stayId:number;personName:string;action:string;oldBedCode?:string;newBedCode?:string;beforeStatus?:string;afterStatus?:string;operatorName:string;reason?:string;operatedAt:string}
export type ResourceAudit={id:number;resourceType:string;resourceId:number;action:string;operatorName:string;operatedAt:string}
export type MeterReading={id:number;buildingId:number;buildingName:string;roomId:number;roomNo:string;readingMonth:string;waterEnd?:number;electricEnd?:number;operatorName:string;updatedAt:string}
export type ImportSummary={received:number;peopleCreated:number;buildingsCreated:number;roomsCreated:number;bedsCreated:number;skipped:string[]}
export type StatisticsItem={name:string;total:number;active:number}
export type DormitoryStatistics={summary:{people:number;buildings:number;rooms:number;beds:number;booked:number;checkedIn:number;checkedOut:number;cancelled:number;freeBeds:number};buildings:StatisticsItem[];categories:StatisticsItem[];statuses:StatisticsItem[]}
export type StayAttachment={id:number;stayId:number;attachmentType:string;originalName:string;contentType:string;fileSize:number;operatorName:string;createdAt:string}
export type FeeRule={waterPrice:number;electricPrice:number;freeWater:number;freeElectric:number;enabled:boolean;operatorName:string;updatedAt:string}
export type FeeBill={id:number;roomId:number;buildingName:string;roomNo:string;billingMonth:string;occupantNames:string;waterUsage:number;electricUsage:number;waterPrice:number;electricPrice:number;freeWater:number;freeElectric:number;waterAmount:number;electricAmount:number;adjustment:number;totalAmount:number;status:'DRAFT'|'CONFIRMED';remark?:string;operatorName:string;updatedAt:string}
const token=()=>sessionStorage.getItem('visitor-authorization')||''
async function request<T>(url:string,init:RequestInit={}):Promise<T>{const response=await fetch(url,{...init,headers:{Authorization:token(),'Content-Type':'application/json',...(init.headers||{})}});if(!response.ok){const body=await response.json().catch(()=>({}));throw new Error(body.detail||body.message||`请求失败（${response.status}）`)}return response.status===204?undefined as T:response.json()}
const base='/api/visitor/dormitory/employee'
export const dormitoryApi={tree:()=>request<{buildings:BuildingNode[]}>(`${base}/resources/tree`),people:(name='')=>request<Person[]>(`${base}/people?name=${encodeURIComponent(name)}`),personStays:(id:number)=>request<Stay[]>(`${base}/people/${id}/stays`),addPerson:(body:Omit<Person,'id'>)=>request<Person>(`${base}/people`,{method:'POST',body:JSON.stringify(body)}),updatePerson:(id:number,body:Omit<Person,'id'>)=>request<Person>(`${base}/people/${id}`,{method:'PUT',body:JSON.stringify(body)}),importPeople:(body:object[])=>request<ImportSummary>(`${base}/imports/people`,{method:'POST',body:JSON.stringify(body)}),importResources:(body:object[])=>request<ImportSummary>(`${base}/imports/resources`,{method:'POST',body:JSON.stringify(body)}),statistics:()=>request<DormitoryStatistics>(`${base}/statistics`),stays:()=>request<Stay[]>(`${base}/stays`),stayAudits:()=>request<StayAudit[]>(`${base}/stay-audits`),resourceAudits:()=>request<ResourceAudit[]>(`${base}/resource-audits`),meterReadings:(month:string)=>request<MeterReading[]>(`${base}/meter-readings?month=${encodeURIComponent(month)}`),saveMeterReadings:(body:object[])=>request<MeterReading[]>(`${base}/meter-readings`,{method:'PUT',body:JSON.stringify(body)}),book:(body:object)=>request<Stay>(`${base}/stays/book`,{method:'POST',body:JSON.stringify(body)}),action:(id:number,action:string,body?:object)=>request<Stay>(`${base}/stays/${id}/${action}`,{method:'POST',body:body?JSON.stringify(body):undefined}),createBuilding:(body:object)=>request<Building>(`${base}/buildings`,{method:'POST',body:JSON.stringify(body)}),updateBuilding:(id:number,body:object)=>request<Building>(`${base}/buildings/${id}`,{method:'PUT',body:JSON.stringify(body)}),createRoom:(body:object)=>request<Room>(`${base}/rooms`,{method:'POST',body:JSON.stringify(body)}),updateRoom:(id:number,body:object)=>request<Room>(`${base}/rooms/${id}`,{method:'PUT',body:JSON.stringify(body)}),createBed:(body:object)=>request<Bed>(`${base}/beds`,{method:'POST',body:JSON.stringify(body)}),updateBed:(id:number,body:object)=>request<Bed>(`${base}/beds/${id}`,{method:'PUT',body:JSON.stringify(body)})}
export const dormitoryExtensionApi={attachments:(stayId:number)=>request<StayAttachment[]>(`${base}/stays/${stayId}/attachments`),uploadAttachment:async(stayId:number,type:string,file:File)=>{const form=new FormData();form.append('file',file);const response=await fetch(`${base}/stays/${stayId}/attachments?type=${encodeURIComponent(type)}`,{method:'POST',headers:{Authorization:token()},body:form});if(!response.ok)throw new Error((await response.json().catch(()=>({}))).detail||'附件上传失败');return response.json() as Promise<StayAttachment>},deleteAttachment:(id:number)=>request<void>(`${base}/attachments/${id}`,{method:'DELETE'}),downloadAttachment:async(a:StayAttachment)=>{const response=await fetch(`${base}/attachments/${a.id}/download`,{headers:{Authorization:token()}});if(!response.ok)throw new Error('附件下载失败');const link=document.createElement('a');link.href=URL.createObjectURL(await response.blob());link.download=a.originalName;link.click();setTimeout(()=>URL.revokeObjectURL(link.href),1000)},feeRule:()=>request<FeeRule>(`${base}/fees/rule`),saveFeeRule:(body:object)=>request<FeeRule>(`${base}/fees/rule`,{method:'PUT',body:JSON.stringify(body)}),feeBills:(month:string)=>request<FeeBill[]>(`${base}/fees/bills?month=${encodeURIComponent(month)}`),generateFeeBills:(month:string)=>request<FeeBill[]>(`${base}/fees/generate?month=${encodeURIComponent(month)}`,{method:'POST'}),updateFeeBill:(id:number,body:object)=>request<FeeBill>(`${base}/fees/bills/${id}`,{method:'PUT',body:JSON.stringify(body)})}
