package com.wansheng.visitor.dormitory;

import static com.wansheng.visitor.dormitory.EmployeeDormitoryModels.*;
import java.sql.*;
import java.time.*;
import java.util.*;
import org.springframework.jdbc.core.*;
import org.springframework.jdbc.support.*;
import org.springframework.stereotype.Repository;

@Repository
class EmployeeDormitoryRepository {
 private final JdbcTemplate jdbc;
 EmployeeDormitoryRepository(JdbcTemplate jdbc){this.jdbc=jdbc;}

 List<Building> buildings(){return jdbc.query("SELECT * FROM dorm_building ORDER BY display_order,id",(r,n)->building(r));}
 Optional<Building> building(long id){return jdbc.query("SELECT * FROM dorm_building WHERE id=?",(r,n)->building(r),id).stream().findFirst();}
 Optional<Building> building(String name,String region){return jdbc.query("SELECT * FROM dorm_building WHERE name=? AND region_name=?",(r,n)->building(r),name,region).stream().findFirst();}
 long addBuilding(BuildingCommand c){return insert("INSERT INTO dorm_building(name,region_name,enabled,display_order) VALUES(?,?,?,?)",c.name(),c.regionName(),value(c.enabled(),true),value(c.displayOrder(),0));}
 int updateBuilding(long id,BuildingCommand c){return jdbc.update("UPDATE dorm_building SET name=?,region_name=?,enabled=?,display_order=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",c.name(),c.regionName(),value(c.enabled(),true),value(c.displayOrder(),0),id);}

 List<Room> rooms(){return jdbc.query("SELECT * FROM dorm_room ORDER BY building_id,display_order,id",(r,n)->room(r,List.of()));}
 Optional<Room> room(long id){return jdbc.query("SELECT * FROM dorm_room WHERE id=?",(r,n)->room(r,bedsByRoom(id)),id).stream().findFirst();}
 Optional<Room> room(long buildingId,String roomNo){return jdbc.query("SELECT * FROM dorm_room WHERE building_id=? AND room_no=?",(r,n)->room(r,bedsByRoom(r.getLong("id"))),buildingId,roomNo).stream().findFirst();}
 long addRoom(RoomCommand c){return insert("INSERT INTO dorm_room(building_id,room_no,floor_no,facing,room_type,livable,cleaning_required,grid_col,grid_row,grid_col_span,grid_row_span,display_order,special_note,enabled) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)",c.buildingId(),c.roomNo(),c.floorNo(),c.facing(),c.roomType(),value(c.livable(),true),value(c.cleaningRequired(),false),c.gridCol(),c.gridRow(),c.gridColSpan(),c.gridRowSpan(),value(c.displayOrder(),0),c.specialNote(),value(c.enabled(),true));}
 int updateRoom(long id,RoomCommand c){return jdbc.update("UPDATE dorm_room SET building_id=?,room_no=?,floor_no=?,facing=?,room_type=?,livable=?,cleaning_required=?,grid_col=?,grid_row=?,grid_col_span=?,grid_row_span=?,display_order=?,special_note=?,enabled=?,version=version+1 WHERE id=?",c.buildingId(),c.roomNo(),c.floorNo(),c.facing(),c.roomType(),value(c.livable(),true),value(c.cleaningRequired(),false),c.gridCol(),c.gridRow(),c.gridColSpan(),c.gridRowSpan(),value(c.displayOrder(),0),c.specialNote(),value(c.enabled(),true),id);}

 List<Bed> bedsByRoom(long roomId){return jdbc.query("SELECT * FROM dorm_bed WHERE room_id=? ORDER BY id",(r,n)->bed(r),roomId);}
 Optional<Bed> bed(long id){return jdbc.query("SELECT * FROM dorm_bed WHERE id=?",(r,n)->bed(r),id).stream().findFirst();}
 Optional<Bed> bed(String code){return jdbc.query("SELECT * FROM dorm_bed WHERE bed_code=?",(r,n)->bed(r),code).stream().findFirst();}
 void lockBed(long id){jdbc.queryForObject("SELECT id FROM dorm_bed WHERE id=? FOR UPDATE",Long.class,id);}
 long addBed(BedCommand c){return insert("INSERT INTO dorm_bed(room_id,label,bed_code,three_piece,enabled) VALUES(?,?,?,?,?)",c.roomId(),c.label(),c.bedCode(),c.threePiece(),value(c.enabled(),true));}
 int updateBed(long id,BedCommand c){return jdbc.update("UPDATE dorm_bed SET room_id=?,label=?,bed_code=?,three_piece=?,enabled=?,version=version+1 WHERE id=?",c.roomId(),c.label(),c.bedCode(),c.threePiece(),value(c.enabled(),true),id);}
 int activeOnBed(long id){return count("SELECT COUNT(*) FROM dorm_stay WHERE bed_id=? AND status IN ('BOOKED','CHECKED_IN')",id);}
 int activeInRoom(long id){return count("SELECT COUNT(*) FROM dorm_stay s JOIN dorm_bed b ON b.id=s.bed_id WHERE b.room_id=? AND s.status IN ('BOOKED','CHECKED_IN')",id);}
 int activeInBuilding(long id){return count("SELECT COUNT(*) FROM dorm_stay s JOIN dorm_bed b ON b.id=s.bed_id JOIN dorm_room r ON r.id=b.room_id WHERE r.building_id=? AND s.status IN ('BOOKED','CHECKED_IN')",id);}
 void resourceAudit(String type,long id,String action,String before,String after,String op){jdbc.update("INSERT INTO dorm_resource_audit(resource_type,resource_id,action,before_value,after_value,operator_name) VALUES(?,?,?,?,?,?)",type,id,action,before,after,op);}
 List<ResourceAudit> resourceAudits(){return jdbc.query("SELECT * FROM dorm_resource_audit ORDER BY operated_at DESC,id DESC LIMIT 500",(r,n)->new ResourceAudit(r.getLong("id"),r.getString("resource_type"),r.getLong("resource_id"),r.getString("action"),r.getString("before_value"),r.getString("after_value"),r.getString("operator_name"),r.getTimestamp("operated_at").toInstant()));}
 List<StayAudit> stayAudits(){return jdbc.query("SELECT a.*,p.name person_name,ob.bed_code old_bed_code,nb.bed_code new_bed_code FROM dorm_stay_audit a JOIN dorm_stay s ON s.id=a.stay_id JOIN dorm_person p ON p.id=s.person_id LEFT JOIN dorm_bed ob ON ob.id=a.old_bed_id LEFT JOIN dorm_bed nb ON nb.id=a.new_bed_id ORDER BY a.operated_at DESC,a.id DESC LIMIT 1000",(r,n)->new StayAudit(r.getLong("id"),r.getLong("stay_id"),r.getString("person_name"),r.getString("action"),r.getString("old_bed_code"),r.getString("new_bed_code"),r.getString("before_status"),r.getString("after_status"),r.getString("operator_name"),r.getString("reason"),r.getTimestamp("operated_at").toInstant()));}
 List<MeterReading> meterReadings(String month){return jdbc.query("SELECT m.*,r.building_id,r.room_no,b.name building_name FROM dorm_meter_reading m JOIN dorm_room r ON r.id=m.room_id JOIN dorm_building b ON b.id=r.building_id WHERE m.reading_month=? ORDER BY b.display_order,r.display_order,r.id",(r,n)->new MeterReading(r.getLong("id"),r.getLong("building_id"),r.getString("building_name"),r.getLong("room_id"),r.getString("room_no"),r.getString("reading_month"),r.getBigDecimal("water_end"),r.getBigDecimal("electric_end"),r.getString("operator_name"),r.getTimestamp("updated_at").toInstant()),month);}
 void saveMeterReading(MeterReadingCommand c,String op){int n=jdbc.update("UPDATE dorm_meter_reading SET water_end=?,electric_end=?,operator_name=?,updated_at=CURRENT_TIMESTAMP WHERE room_id=? AND reading_month=?",c.waterEnd(),c.electricEnd(),op,c.roomId(),c.readingMonth());if(n==0)jdbc.update("INSERT INTO dorm_meter_reading(room_id,reading_month,water_end,electric_end,operator_name) VALUES(?,?,?,?,?)",c.roomId(),c.readingMonth(),c.waterEnd(),c.electricEnd(),op);}

 List<Person> people(String name){String q="SELECT p.*,p.id person_id FROM dorm_person p "+(name==null||name.isBlank()?"":"WHERE name LIKE ? ")+"ORDER BY updated_at DESC,id DESC";return name==null||name.isBlank()?jdbc.query(q,(r,n)->person(r)):jdbc.query(q,(r,n)->person(r),"%"+name.trim()+"%");}
 Optional<Person> person(long id){return jdbc.query("SELECT p.*,p.id person_id FROM dorm_person p WHERE id=?",(r,n)->person(r),id).stream().findFirst();}
 Optional<Person> person(String name,String department){return jdbc.query("SELECT p.*,p.id person_id FROM dorm_person p WHERE name=? AND department=?",(r,n)->person(r),name,department).stream().findFirst();}
 long addPerson(PersonCommand c){return insert("INSERT INTO dorm_person(name,center_name,department,gender,category,position_name,rank_name) VALUES(?,?,?,?,?,?,?)",c.name(),c.centerName(),c.department(),c.gender(),c.category(),c.positionName(),c.rankName());}
 int updatePerson(long id,PersonCommand c){return jdbc.update("UPDATE dorm_person SET name=?,center_name=?,department=?,gender=?,category=?,position_name=?,rank_name=?,updated_at=CURRENT_TIMESTAMP WHERE id=?",c.name(),c.centerName(),c.department(),c.gender(),c.category(),c.positionName(),c.rankName(),id);}

 boolean occupied(long bedId,long exceptStay){Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM dorm_stay WHERE bed_id=? AND status IN ('BOOKED','CHECKED_IN') AND id<>?",Integer.class,bedId,exceptStay);return n!=null&&n>0;}
 boolean mixedGender(long bedId,long personId,long exceptStay){Integer n=jdbc.queryForObject("SELECT COUNT(*) FROM dorm_stay s JOIN dorm_person p ON p.id=s.person_id JOIN dorm_bed b ON b.id=s.bed_id JOIN dorm_bed target ON target.id=? WHERE b.room_id=target.room_id AND s.status IN ('BOOKED','CHECKED_IN') AND s.id<>? AND p.gender<>(SELECT gender FROM dorm_person WHERE id=?)",Integer.class,bedId,exceptStay,personId);return n!=null&&n>0;}
 long book(BookCommand c,String op){return insert("INSERT INTO dorm_stay(person_id,bed_id,status,application_code,liaison,bed_type,cost_cut,promise_signed,move_in_water,move_in_electric,planned_move_in,planned_move_out,special_note,remark,operator_name) VALUES(?,?,'BOOKED',?,?,?,?,?,?,?,?,?,?,?,?)",c.personId(),c.bedId(),c.applicationCode(),c.liaison(),c.bedType(),c.costCut(),c.promiseSigned(),c.moveInWater(),c.moveInElectric(),c.plannedMoveIn(),c.plannedMoveOut(),c.specialNote(),c.remark(),op);}
 Optional<Stay> stay(long id){return jdbc.query("SELECT s.*,p.name,p.center_name,p.department,p.gender,p.category,p.position_name,p.rank_name,b.room_id,b.label,b.bed_code,b.three_piece,b.enabled bed_enabled FROM dorm_stay s JOIN dorm_person p ON p.id=s.person_id JOIN dorm_bed b ON b.id=s.bed_id WHERE s.id=?",(r,n)->stay(r),id).stream().findFirst();}
 List<Stay> stays(String status,Long buildingId,String name){StringBuilder q=new StringBuilder("SELECT s.*,p.name,p.center_name,p.department,p.gender,p.category,p.position_name,p.rank_name,b.room_id,b.label,b.bed_code,b.three_piece,b.enabled bed_enabled FROM dorm_stay s JOIN dorm_person p ON p.id=s.person_id JOIN dorm_bed b ON b.id=s.bed_id JOIN dorm_room rm ON rm.id=b.room_id WHERE 1=1");List<Object>a=new ArrayList<>();if(status!=null&&!status.isBlank()){q.append(" AND s.status=?");a.add(status);}if(buildingId!=null){q.append(" AND rm.building_id=?");a.add(buildingId);}if(name!=null&&!name.isBlank()){q.append(" AND p.name LIKE ?");a.add("%"+name.trim()+"%");}q.append(" ORDER BY s.updated_at DESC,s.id DESC");return jdbc.query(q.toString(),(r,n)->stay(r),a.toArray());}
 List<Stay> staysByPerson(long personId){return jdbc.query("SELECT s.*,p.name,p.center_name,p.department,p.gender,p.category,p.position_name,p.rank_name,b.room_id,b.label,b.bed_code,b.three_piece,b.enabled bed_enabled FROM dorm_stay s JOIN dorm_person p ON p.id=s.person_id JOIN dorm_bed b ON b.id=s.bed_id WHERE s.person_id=? ORDER BY s.updated_at DESC,s.id DESC",(r,n)->stay(r),personId);}
 int transition(long id,String from,String to,String op){String stamp="CHECKED_IN".equals(to)?",checked_in_at=CURRENT_TIMESTAMP":"CHECKED_OUT".equals(to)?",checked_out_at=CURRENT_TIMESTAMP":"";return jdbc.update("UPDATE dorm_stay SET status=?,operator_name=?,updated_at=CURRENT_TIMESTAMP,version=version+1"+stamp+" WHERE id=? AND status=?",to,op,id,from);}
 int transfer(long id,long bedId,String op){return jdbc.update("UPDATE dorm_stay SET bed_id=?,operator_name=?,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=? AND status IN ('BOOKED','CHECKED_IN')",bedId,op,id);}
 int extend(long id,LocalDate date,String op){return jdbc.update("UPDATE dorm_stay SET planned_move_out=?,operator_name=?,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=? AND status IN ('BOOKED','CHECKED_IN')",date,op,id);}
 int checkout(long id,CheckoutCommand c,String op){return jdbc.update("UPDATE dorm_stay SET status='CHECKED_OUT',move_out_water=?,move_out_electric=?,checked_out_at=CURRENT_TIMESTAMP,operator_name=?,updated_at=CURRENT_TIMESTAMP,version=version+1 WHERE id=? AND status='CHECKED_IN'",c.moveOutWater(),c.moveOutElectric(),op,id);}
 void audit(long id,String action,Long oldBed,Long newBed,String before,String after,String op,String reason){jdbc.update("INSERT INTO dorm_stay_audit(stay_id,action,old_bed_id,new_bed_id,before_status,after_status,operator_name,reason) VALUES(?,?,?,?,?,?,?,?)",id,action,oldBed,newBed,before,after,op,reason);}

 private long insert(String sql,Object...args){KeyHolder h=new GeneratedKeyHolder();jdbc.update(c->{PreparedStatement p=c.prepareStatement(sql,new String[]{"id"});for(int i=0;i<args.length;i++)p.setObject(i+1,args[i]);return p;},h);return Objects.requireNonNull(h.getKey()).longValue();}
 private int count(String sql,Object...args){Integer n=jdbc.queryForObject(sql,Integer.class,args);return n==null?0:n;}
 private static boolean value(Boolean v,boolean d){return v==null?d:v;} private static int value(Integer v,int d){return v==null?d:v;}
 private static Building building(ResultSet r)throws SQLException{return new Building(r.getLong("id"),r.getString("name"),r.getString("region_name"),r.getBoolean("enabled"),r.getInt("display_order"));}
 private static Room room(ResultSet r,List<Bed>b)throws SQLException{return new Room(r.getLong("id"),r.getLong("building_id"),r.getString("room_no"),r.getInt("floor_no"),r.getString("facing"),r.getString("room_type"),r.getBoolean("livable"),r.getBoolean("cleaning_required"),(Integer)r.getObject("grid_col"),(Integer)r.getObject("grid_row"),(Integer)r.getObject("grid_col_span"),(Integer)r.getObject("grid_row_span"),r.getInt("display_order"),r.getString("special_note"),r.getBoolean("enabled"),b);}
 private static Bed bed(ResultSet r)throws SQLException{return new Bed(r.getLong("id"),r.getLong("room_id"),r.getString("label"),r.getString("bed_code"),r.getString("three_piece"),r.getBoolean("enabled"));}
 private static Person person(ResultSet r)throws SQLException{return new Person(r.getLong("person_id"),r.getString("name"),r.getString("center_name"),r.getString("department"),r.getString("gender"),r.getString("category"),r.getString("position_name"),r.getString("rank_name"));}
 private static Stay stay(ResultSet r)throws SQLException{Person p=person(r);Bed b=new Bed(r.getLong("bed_id"),r.getLong("room_id"),r.getString("label"),r.getString("bed_code"),r.getString("three_piece"),r.getBoolean("bed_enabled"));return new Stay(r.getLong("id"),p,b,StayStatus.valueOf(r.getString("status")),r.getString("application_code"),r.getString("liaison"),r.getString("bed_type"),r.getBoolean("cost_cut"),(Boolean)r.getObject("promise_signed"),r.getBigDecimal("move_in_water"),r.getBigDecimal("move_in_electric"),r.getBigDecimal("move_out_water"),r.getBigDecimal("move_out_electric"),r.getObject("planned_move_in",LocalDate.class),r.getObject("planned_move_out",LocalDate.class),instant(r,"checked_in_at"),instant(r,"checked_out_at"),r.getString("special_note"),r.getString("remark"),r.getLong("version"));}
 private static Instant instant(ResultSet r,String c)throws SQLException{Timestamp t=r.getTimestamp(c);return t==null?null:t.toInstant();}
}
