<script setup lang="ts">
import{computed,onMounted,ref}from'vue'
type Item={visitId:string;visitorName:string;mobile:string;hostName:string;plateNumber?:string;vehicleEnteringFactory:boolean;oaStatus:string;guardStatus:string;entryTime?:string;exitTime?:string;entryOperator?:string;exitOperator?:string}
const statuses=[{key:'WAITING_ENTRY',label:'待入厂'},{key:'IN_FACTORY',label:'当前在厂'},{key:'EXITED',label:'离场记录'}]
const status=ref('WAITING_ENTRY'),all=ref<Record<string,Item[]>>({WAITING_ENTRY:[],IN_FACTORY:[],EXITED:[]}),keyword=ref(''),page=ref(1),pageSize=10,loading=ref(false),error=ref(''),selected=ref<Item|null>(null),acting=ref('')
const auth=()=>sessionStorage.getItem('visitor-authorization')||''
const filtered=computed(()=>{const q=keyword.value.trim().toLowerCase();return(all.value[status.value]||[]).filter(r=>!q||[r.visitorName,r.mobile,r.hostName,r.plateNumber,r.visitId].some(v=>v?.toLowerCase().includes(q)))})
const pages=computed(()=>Math.max(1,Math.ceil(filtered.value.length/pageSize))),rows=computed(()=>filtered.value.slice((page.value-1)*pageSize,page.value*pageSize))
const counts=computed(()=>Object.fromEntries(statuses.map(s=>[s.key,all.value[s.key]?.length||0])))
const statusText:Record<string,string>={WAITING_ENTRY:'待入厂',IN_FACTORY:'当前在厂',EXITED:'已离场',NOT_STARTED:'未开始',PROCESSING:'审批中',APPROVED:'已通过',REJECTED:'已驳回',FAILED:'处理失败'}
function fmt(v?:string){return v?new Intl.DateTimeFormat('zh-CN',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v)):'—'}
async function load(){loading.value=true;error.value='';try{const result=await Promise.all(statuses.map(async s=>{const r=await fetch(`/api/visitor/guard/records?status=${s.key}`,{headers:{Authorization:auth()}});if(!r.ok){if(r.status===503)throw new Error('门卫记录展示时机尚待业务确认（Q-008），当前环境未开放列表');throw new Error('门卫记录加载失败')}return[s.key,await r.json()]as const}));all.value=Object.fromEntries(result)}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}}
function switchTab(key:string){status.value=key;page.value=1;selected.value=null}
async function act(item:Item,action:'entry'|'exit'){const label=action==='entry'?'确认入厂':'确认离场';if(!window.confirm(`${label}：${item.visitorName}？操作时间由服务器记录。`))return;acting.value=item.visitId;error.value='';const user=JSON.parse(sessionStorage.getItem('visitor-user')||'{}');try{const r=await fetch(`/api/visitor/guard/records/${item.visitId}/${action}`,{method:'POST',headers:{Authorization:auth(),'X-Operator':user.username||'unknown'}});if(!r.ok)throw new Error(r.status===409?'记录状态已变化，请刷新后重试':'操作失败');selected.value=null;await load()}catch(e){error.value=e instanceof Error?e.message:'操作失败'}finally{acting.value=''}}
onMounted(load)
</script>
<template><header class="page-head"><div><p class="eyebrow">GUARD WORKBENCH</p><h2>门卫工作台</h2><p class="muted">查看授权访客信息，手动确认入厂与离场。</p></div><button class="secondary-button" :disabled="loading" @click="load">刷新记录</button></header><div class="guard-summary"><button v-for="s in statuses" :key="s.key" :class="['summary-tab',{active:status===s.key}]" @click="switchTab(s.key)"><span>{{s.label}}</span><strong>{{counts[s.key]}}</strong></button></div><section class="toolbar"><input v-model="keyword" placeholder="搜索姓名、手机号、被访人、车牌或编号" @input="page=1"/><span class="muted">共 {{filtered.length}} 条</span></section><p v-if="error" class="notice-error">{{error}}</p><div class="table-wrap"><table><thead><tr><th>访客</th><th>联系方式</th><th>被访人</th><th>车辆</th><th>OA结果</th><th>入厂时间</th><th>离场时间</th><th>操作</th></tr></thead><tbody><tr v-if="loading"><td colspan="8" class="empty-cell">正在加载…</td></tr><tr v-else-if="!rows.length"><td colspan="8" class="empty-cell">暂无符合条件的记录</td></tr><tr v-for="r in rows" :key="r.visitId"><td><button class="link-button" @click="selected=r">{{r.visitorName}}</button><small class="table-sub">{{r.visitId}}</small></td><td>{{r.mobile}}</td><td>{{r.hostName}}</td><td>{{r.plateNumber||'无车牌'}}<small class="table-sub">{{r.vehicleEnteringFactory?'车辆进厂':'车辆不进厂'}}</small></td><td><span :class="['status-pill',r.oaStatus.toLowerCase()]">{{statusText[r.oaStatus]||r.oaStatus}}</span></td><td>{{fmt(r.entryTime)}}</td><td>{{fmt(r.exitTime)}}</td><td><button v-if="r.guardStatus==='WAITING_ENTRY'" class="table-action" :disabled="acting===r.visitId" @click="act(r,'entry')">确认入厂</button><button v-else-if="r.guardStatus==='IN_FACTORY'" class="table-action danger" :disabled="acting===r.visitId" @click="act(r,'exit')">确认离场</button><span v-else class="muted">已完成</span></td></tr></tbody></table></div><div class="pagination"><button :disabled="page<=1" @click="page--">上一页</button><span>第 {{page}} / {{pages}} 页</span><button :disabled="page>=pages" @click="page++">下一页</button></div><div v-if="selected" class="drawer-backdrop" @click.self="selected=null"><aside class="detail-drawer"><button class="drawer-close" @click="selected=null">×</button><p class="eyebrow">VISIT DETAIL</p><h2>{{selected.visitorName}}</h2><dl><dt>来访编号</dt><dd>{{selected.visitId}}</dd><dt>手机号</dt><dd>{{selected.mobile}}</dd><dt>被访人</dt><dd>{{selected.hostName}}</dd><dt>车牌号</dt><dd>{{selected.plateNumber||'—'}}</dd><dt>车辆进厂</dt><dd>{{selected.vehicleEnteringFactory?'是':'否'}}</dd><dt>OA审批结果</dt><dd>{{statusText[selected.oaStatus]||selected.oaStatus}}（只读）</dd><dt>入厂记录</dt><dd>{{fmt(selected.entryTime)}} {{selected.entryOperator||''}}</dd><dt>离场记录</dt><dd>{{fmt(selected.exitTime)}} {{selected.exitOperator||''}}</dd></dl></aside></div></template>
