<script setup lang="ts">
import { onMounted, reactive, ref } from 'vue'
const loadingConfiguration=ref(true),submitting=ref(false),error=ref(''),copied=ref(false)
const result=ref<{visitId:string;notice:string}|null>(null)
const form=reactive({visitorName:'',mobile:'',hostName:'',hostDepartment:'',visitReason:'',accommodationRequired:false,hasVehicle:false,plateNumber:'',vehicleEnteringFactory:false,phoneNotificationRequested:false})
onMounted(async()=>{try{const r=await fetch('/api/visitor/registrations/configuration');if(!r.ok)throw new Error('登记服务暂不可用');await r.json()}catch(e){error.value=e instanceof Error?e.message:'登记服务暂不可用'}finally{loadingConfiguration.value=false}})
async function submit(){submitting.value=true;error.value='';try{const r=await fetch('/api/visitor/registrations',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({...form,plateNumber:form.hasVehicle?form.plateNumber:null,vehicleEnteringFactory:form.hasVehicle&&form.vehicleEnteringFactory})});if(!r.ok){const p=await r.json().catch(()=>({}));throw new Error(p.detail||p.message||'提交失败，请检查填写内容')}result.value=await r.json();window.scrollTo({top:0,behavior:'smooth'})}catch(e){error.value=e instanceof Error?e.message:'提交失败'}finally{submitting.value=false}}
async function copyVisitId(){if(!result.value)return;await navigator.clipboard.writeText(result.value.visitId);copied.value=true;setTimeout(()=>copied.value=false,1600)}
function again(){result.value=null;copied.value=false;Object.assign(form,{visitorName:'',mobile:'',hostName:'',hostDepartment:'',visitReason:'',accommodationRequired:false,hasVehicle:false,plateNumber:'',vehicleEnteringFactory:false,phoneNotificationRequested:false})}
</script>
<template><div class="registration-page"><header class="mobile-brand"><span class="brand-mark">万</span><div><strong>万盛股份</strong><small>访客登记</small></div></header>
<section v-if="result" class="panel result-panel"><div class="success-mark">✓</div><p class="eyebrow">登记提交成功</p><h1>感谢您的配合</h1><p class="result-lead">来访申请已提交，请保存下方来访编号。</p><button class="visit-id" type="button" @click="copyVisitId"><span>{{result.visitId}}</span><small>{{copied?'已复制':'点击复制'}}</small></button><div class="result-steps"><div><b>1</b><span>等待审批与现场确认</span></div><div><b>2</b><span>到厂后向门卫出示来访编号</span></div></div><p class="result-notice">{{result.notice}}</p><button class="secondary-button result-again" type="button" @click="again">继续登记其他访客</button></section>
<form v-else class="panel registration-panel" @submit.prevent="submit"><div class="registration-intro"><p class="eyebrow">VISITOR REGISTRATION</p><h1>来访申请</h1><p>请准确填写信息，带 <em>*</em> 的项目为必填项。</p></div>
<section class="form-section"><h2><span>1</span>访客信息</h2><div class="form-grid"><label>姓名 <em>*</em><input v-model.trim="form.visitorName" maxlength="100" autocomplete="name" placeholder="请输入真实姓名" required/></label><label>手机号 <em>*</em><input v-model.trim="form.mobile" maxlength="30" inputmode="tel" autocomplete="tel" placeholder="用于现场联系" required/></label></div></section>
<section class="form-section"><h2><span>2</span>来访信息</h2><div class="form-grid"><label>被访人 <em>*</em><input v-model.trim="form.hostName" maxlength="100" placeholder="请输入被访人姓名" required/></label><label>被访部门 <em>*</em><input v-model.trim="form.hostDepartment" maxlength="150" placeholder="请输入部门名称" required/></label><label class="wide">来访事由 <em>*</em><textarea v-model.trim="form.visitReason" maxlength="500" rows="4" placeholder="请简要说明来访目的" required/></label></div></section>
<section class="form-section"><h2><span>3</span>其他信息</h2><div class="option-cards"><label :class="['option-card',{selected:form.accommodationRequired}]"><input v-model="form.accommodationRequired" type="checkbox"/><span><b>需要住宿</b><small>需要安排厂区宿舍</small></span></label><label :class="['option-card',{selected:form.hasVehicle}]"><input v-model="form.hasVehicle" type="checkbox"/><span><b>携带车辆</b><small>登记来访车辆信息</small></span></label></div><div v-if="form.hasVehicle" class="vehicle-fields"><label>车牌号 <em>*</em><input v-model.trim="form.plateNumber" maxlength="30" placeholder="例如：浙A12345" required/></label><label class="choice"><input v-model="form.vehicleEnteringFactory" type="checkbox"/> 车辆需要进入厂区</label></div></section>
<p class="privacy-note">提交即表示您确认所填信息真实有效。信息仅用于本次来访管理。</p><p v-if="error" class="notice-error">{{error}}</p><button class="submit-registration" :disabled="submitting||loadingConfiguration">{{submitting?'正在提交…':'确认提交申请'}}</button></form></div></template>
