<script setup lang="ts">
import{onMounted,reactive,ref}from'vue'
type Account={id:number;username:string;displayName:string;role:string;enabled:boolean;createdAt:string}
const roles=[['GUARD','门卫'],['DORM_ADMIN','宿舍管理员'],['ADMIN','后台管理员'],['SYSTEM_ADMIN','系统管理员']],users=ref<Account[]>([]),loading=ref(false),error=ref(''),message=ref(''),editing=ref<Account|null>(null),passwordUser=ref<Account|null>(null)
const create=reactive({username:'',displayName:'',password:'',role:'GUARD'}),edit=reactive({displayName:'',role:'GUARD',enabled:true}),newPassword=ref('')
const auth=()=>sessionStorage.getItem('visitor-authorization')||'',headers=()=>({Authorization:auth(),'Content-Type':'application/json'})
async function payload(r:Response){if(r.ok)return r.status===204?null:r.json();const p=await r.json().catch(()=>({}));throw new Error(p.detail||p.message||`操作失败（${r.status}）`)}
async function load(){loading.value=true;error.value='';try{users.value=await payload(await fetch('/api/visitor/auth/users',{headers:headers()}))}catch(e){error.value=e instanceof Error?e.message:'加载失败'}finally{loading.value=false}}
async function add(){error.value='';message.value='';try{await payload(await fetch('/api/visitor/auth/users',{method:'POST',headers:headers(),body:JSON.stringify(create)}));Object.assign(create,{username:'',displayName:'',password:'',role:'GUARD'});message.value='账号创建成功';await load()}catch(e){error.value=e instanceof Error?e.message:'创建失败'}}
function openEdit(u:Account){editing.value=u;Object.assign(edit,{displayName:u.displayName,role:u.role,enabled:u.enabled})}
async function save(){if(!editing.value)return;try{await payload(await fetch(`/api/visitor/auth/users/${editing.value.username}`,{method:'PUT',headers:headers(),body:JSON.stringify(edit)}));editing.value=null;message.value='账号已更新';await load()}catch(e){error.value=e instanceof Error?e.message:'更新失败'}}
async function reset(){if(!passwordUser.value)return;try{await payload(await fetch(`/api/visitor/auth/users/${passwordUser.value.username}/password`,{method:'PUT',headers:headers(),body:JSON.stringify({password:newPassword.value})}));passwordUser.value=null;newPassword.value='';message.value='密码已重置'}catch(e){error.value=e instanceof Error?e.message:'重置失败'}}
async function remove(u:Account){if(!confirm(`确认删除账号 ${u.username}？`))return;try{await payload(await fetch(`/api/visitor/auth/users/${u.username}`,{method:'DELETE',headers:headers()}));message.value='账号已删除';await load()}catch(e){error.value=e instanceof Error?e.message:'删除失败'}}
const roleName=(r:string)=>roles.find(x=>x[0]===r)?.[1]||r
onMounted(load)
</script>
<template><header class="page-head"><div><p class="eyebrow">SYSTEM MANAGEMENT</p><h2>用户与角色管理</h2><p class="muted">创建内部账号、分配岗位角色并控制启停状态。</p></div><button class="secondary-button" @click="load">刷新</button></header><p v-if="error" class="notice-error">{{error}}</p><p v-if="message" class="notice-success">{{message}}</p><section class="panel wide-panel account-create"><h3>新建账号</h3><form class="account-form" @submit.prevent="add"><label>登录名<input v-model.trim="create.username" pattern="[A-Za-z0-9._-]{3,50}" required placeholder="如 guard-02"/></label><label>姓名<input v-model.trim="create.displayName" maxlength="100" required/></label><label>初始密码<input v-model="create.password" type="password" minlength="8" required/></label><label>角色<select v-model="create.role"><option v-for="r in roles" :key="r[0]" :value="r[0]">{{r[1]}}</option></select></label><button>创建账号</button></form></section><section class="panel wide-panel user-list"><div class="section-title"><h3>账号列表</h3><span class="muted">{{users.length}} 个账号</span></div><div class="table-wrap"><table><thead><tr><th>登录名</th><th>姓名</th><th>角色</th><th>状态</th><th>创建时间</th><th>操作</th></tr></thead><tbody><tr v-if="loading"><td colspan="6" class="empty-cell">正在加载…</td></tr><tr v-for="u in users" :key="u.id"><td><code>{{u.username}}</code></td><td>{{u.displayName}}</td><td>{{roleName(u.role)}}</td><td><span :class="['status-pill',u.enabled?'approved':'disabled']">{{u.enabled?'启用':'停用'}}</span></td><td>{{new Date(u.createdAt).toLocaleString('zh-CN')}}</td><td class="row-actions"><button class="link-button" @click="openEdit(u)">编辑</button><button class="link-button" @click="passwordUser=u">重置密码</button><button class="link-button danger-text" @click="remove(u)">删除</button></td></tr></tbody></table></div></section><div v-if="editing" class="modal-backdrop"><form class="panel modal-card" @submit.prevent="save"><h3>编辑 {{editing.username}}</h3><label>姓名<input v-model.trim="edit.displayName" required/></label><label>角色<select v-model="edit.role"><option v-for="r in roles" :key="r[0]" :value="r[0]">{{r[1]}}</option></select></label><label class="choice"><input v-model="edit.enabled" type="checkbox"/> 启用账号</label><div class="modal-actions"><button type="button" class="secondary-button" @click="editing=null">取消</button><button>保存</button></div></form></div><div v-if="passwordUser" class="modal-backdrop"><form class="panel modal-card" @submit.prevent="reset"><h3>重置 {{passwordUser.username}} 的密码</h3><label>新密码<input v-model="newPassword" type="password" minlength="8" required/></label><div class="modal-actions"><button type="button" class="secondary-button" @click="passwordUser=null">取消</button><button>确认重置</button></div></form></div></template>
